### ISSUE TITLE
Support M1 Macs

### ISSUE THREAD

**Issue by mattwthompson** [conda-forge/mdtraj-feedstock#36]
This will probably require a new release; I think https://github.com/mdtraj/mdtraj/issues/1679 might be the first indication of it actually building on M1 in development environments

**Comment by mattwthompson** [comment]
Once https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2159 is merged, the bots will attempt to build and they'll probably fail. If they do, we'll have to make a new release

**Comment by sroet** [comment]
closed by #37
