### ISSUE TITLE
Add `mda-xdrlib` to `meta.yml`

### ISSUE THREAD

**Issue by chrisjonesBSU** [conda-forge/mdtraj-feedstock#62]
### Comment:

Just a reminder for the next release since https://github.com/mdtraj/mdtraj/pull/1911 and https://github.com/mdtraj/mdtraj/pull/1913 have been merged.

**Comment by jeremyleung521** [comment]
We've since removed `mda-xdrlib`, so I think this is no longer relevant. https://github.com/mdtraj/mdtraj/pull/1919

Probably could be closed by someone with permission.
